//! The Terminal application backend.
//!
//! Almost everything lives in `slate-runtime`: the portable bootstrap, window
//! chrome, logging, and the commands the custom title bar needs. What remains
//! here is only what is specific to Terminal, which is what keeps the three
//! applications consistent as they grow apart.

use slate_core::KnownApp;

/// Starts the application.
///
/// # Panics
///
/// Panics if the portable environment cannot be prepared or Tauri cannot
/// start. Both mean the application cannot run at all — there is no degraded
/// mode in which a window exists but has nowhere to write — so failing loudly
/// with the reason beats a window that silently misbehaves.
// Failing loudly is the intended behaviour, and is documented above: there
// is no degraded mode in which a window exists but has nowhere to write.
#[allow(clippy::expect_used)]
pub fn run() {
    // Must be first: WebView2 reads its environment when the first webview is
    // created, so setting it later silently has no effect (ADR 0005).
    let state = slate_runtime::bootstrap(KnownApp::Terminal.id())
        .expect("the portable environment could not be prepared");

    tauri::Builder::default()
        .manage(state)
        .invoke_handler(tauri::generate_handler![
            slate_runtime::commands::window::slate_window_state,
            slate_runtime::commands::window::slate_window_minimize,
            slate_runtime::commands::window::slate_window_toggle_maximize,
            slate_runtime::commands::window::slate_window_close,
            slate_runtime::commands::window::slate_window_hide,
            slate_runtime::commands::window::slate_window_show,
            slate_runtime::commands::window::slate_window_set_always_on_top,
            slate_runtime::commands::window::slate_window_start_drag,
            slate_runtime::commands::window::slate_window_persist_geometry,
            slate_runtime::commands::runtime::slate_runtime_info,
            slate_runtime::commands::runtime::slate_set_theme,
            slate_runtime::commands::runtime::slate_reload_config,
            slate_runtime::commands::preferences::slate_open_config_file,
            slate_runtime::commands::tray::slate_tray_menu_ready,
            slate_runtime::commands::tray::slate_tray_menu_dismiss,
            slate_runtime::commands::tray::slate_tray_show_main_window,
            slate_runtime::commands::tray::slate_tray_hide_main_window,
            slate_runtime::commands::tray::slate_tray_main_window_is_visible,
            slate_runtime::commands::tray::slate_tray_quit,
        ])
        // Preferences reveals this app's own config file rather than opening a
        // settings window that does not exist yet (see
        // `slate_runtime::commands::preferences`).
        .plugin(tauri_plugin_opener::init())
        // Each application ships its own tray glyphs — one per Windows
        // taskbar theme, since Windows never tints a tray icon itself, and a
        // single colour disappears against one of the two. Generated by
        // `scripts/bun-tray-icons.ts`; three identical icons in one
        // notification area would be three icons nobody can tell apart.
        .setup(slate_runtime::setup_with_tray(slate_runtime::TrayIcons {
            for_dark_theme: include_bytes!("../icons/tray-dark-theme.png"),
            for_light_theme: include_bytes!("../icons/tray-light-theme.png"),
        }))
        .run(tauri::generate_context!())
        .expect("the application failed to start");
}
